name: Build and Test Android App
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Android SDK
        run: |
          sudo apt-get update && sudo apt-get install unzip
          wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
          unzip sdk-tools-linux-4333796.zip -d android-sdk
          echo 'export ANDROID_HOME=$PWD/android-sdk' >> $GITHUB_ENV
          echo 'export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools' >> $GITHUB_ENV
        env:
          JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build app
        run: ./gradlew assemble
      - name: Store APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: app-debug.apk
      - name: Clone repository with Serenity and Appium tests
        run: git clone git@github.com:99minutos/Automation_App_Veloz.git
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Android SDK
        run: |
          sudo apt-get update && sudo apt-get install unzip
          wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
          unzip sdk-tools-linux-4333796.zip -d android-sdk
          echo 'export ANDROID_HOME=$PWD/android-sdk' >> $GITHUB_ENV
          echo 'export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools' >> $GITHUB_ENV
        env:
          JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      - name: Set up Appium
        run: |
          npm install -g appium
      - name: Run Appium tests
        run: |
          appium &
          adb devices
          cd Automation_App_Veloz
          mv ../app-debug.apk Automation_App_Veloz/src/test/resources/app.apk
          ./gradlew clean test
